### ISSUE TITLE
6/17(토) 할 것

### ISSUE THREAD

**Issue by wjdrbs96** [mash-up-kr/JSMR-Spring#14]
- [x] 패키지 구조 어떻게 할지 리뷰 + 각 모듈 어떻게 사용할지 논의
- [x] ERD 다이어그램 리뷰
- [x] JPA Entity 설계 및 테이블 생성
- [x] ExceptionHandler 구조 리뷰
- [x] JWT 어떻게 사용할지 구조 리뷰
- [x] API 역할 분담

**Comment by xonmin** [comment]
- [x] NCloud 서버 / K8S / Docker 논의 

## 와이어프레임 
https://www.figma.com/file/ZPawRYDDT4mgsdhtoXoxOy/%EC%A0%95%EC%8B%A0%EB%A8%B8%EB%A6%AC-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8?node-id=3%3A66
